spring:
  application:
    name: 'PictureService'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQLDialect'
    hibernate:
      ddl-auto: 'update'
  servlet:
    multipart:
      max-file-size: '30MB'
      max-request-size: '30MB'
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    username: 'root'
    password: 'secret'
    url: 'jdbc:mysql://picture-service-database:3306/picture-service?createDatabaseIfNotExist=true'
