spring:
  application:
    name: 'PictureService'
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        dialect: 'org.hibernate.dialect.MySQLDialect'
    hibernate:
      ddl-auto: 'update'
  servlet:
    multipart:
      max-file-size: '30MB'
      max-request-size: '30MB'
#  datasource:
#    driver-class-name: 'com.mysql.cj.jdbc.Driver'
#    username: 'root'
#    password: 'secret'
#    url: 'jdbc:mysql://localhost:3306/venue-service?createDatabaseIfNotExist=true'

logging:
  level:
    org:
      hibernate:
        type: trace
